# Generated by Django 2.0.2 on 2018-07-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0055_auto_20180510_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C3', 'Category 3'), ('C1', 'Category 1'), ('C5', 'Category 5'), ('C2', 'Category 2'), ('C4', 'Category 4')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('independent', 'Independent'), ('wholesale', 'Wholesale'), ('service', 'Service'), ('manufacturer', 'Manufacturer'), ('retail', 'Retail')], default='manufacturer', max_length=12),
        ),
    ]
