# Generated by Django 2.0.2 on 2018-08-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0056_auto_20180714_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C4', 'Category 4'), ('C2', 'Category 2'), ('C1', 'Category 1'), ('C3', 'Category 3'), ('C5', 'Category 5')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyCategory',
            field=models.CharField(choices=[('b2c', 'Business-to-Consumer'), ('b2b', 'Business-to-Business')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('retail', 'Retail'), ('service', 'Service'), ('independent', 'Independent'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer')], default='manufacturer', max_length=12),
        ),
    ]
