# Generated by Django 2.0.2 on 2018-08-14 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0057_auto_20180801_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(default='', max_length=1000)),
                ('image1', models.FileField(upload_to='products')),
                ('image2', models.FileField(upload_to='products')),
                ('image3', models.FileField(upload_to='products')),
                ('image4', models.FileField(upload_to='products')),
                ('image5', models.FileField(upload_to='products')),
                ('image6', models.FileField(upload_to='products')),
                ('caption1', models.CharField(default='', max_length=200)),
                ('caption2', models.CharField(default='', max_length=200)),
                ('caption3', models.CharField(default='', max_length=200)),
                ('caption4', models.CharField(default='', max_length=200)),
                ('caption5', models.CharField(default='', max_length=200)),
                ('caption6', models.CharField(default='', max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C1', 'Category 1'), ('C5', 'Category 5'), ('C3', 'Category 3'), ('C2', 'Category 2'), ('C4', 'Category 4')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('service', 'Service'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer'), ('independent', 'Independent'), ('retail', 'Retail')], default='manufacturer', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyusaapp.Gig'),
        ),
    ]
