# Generated by Django 2.0.2 on 2018-08-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0059_auto_20180815_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C2', 'Category 2'), ('C5', 'Category 5'), ('C1', 'Category 1'), ('C4', 'Category 4'), ('C3', 'Category 3')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('wholesale', 'Wholesale'), ('retail', 'Retail'), ('manufacturer', 'Manufacturer'), ('independent', 'Independent'), ('service', 'Service')], default='manufacturer', max_length=12),
        ),
    ]
