# Generated by Django 2.0.2 on 2018-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0060_auto_20180815_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C3', 'Category 3'), ('C2', 'Category 2'), ('C5', 'Category 5'), ('C4', 'Category 4'), ('C1', 'Category 1')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyContactEmail',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('retail', 'Retail'), ('independent', 'Independent'), ('service', 'Service'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer')], default='manufacturer', max_length=12),
        ),
    ]
