# Generated by Django 2.0.2 on 2018-09-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0061_auto_20180916_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C3', 'Category 3'), ('C2', 'Category 2'), ('C1', 'Category 1'), ('C5', 'Category 5'), ('C4', 'Category 4')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyCategory',
            field=models.CharField(choices=[('b2b', 'Business-to-Business'), ('b2c', 'Business-to-Consumer')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('independent', 'Independent'), ('wholesale', 'Wholesale'), ('service', 'Service'), ('retail', 'Retail')], default='manufacturer', max_length=12),
        ),
    ]
