# Generated by Django 2.0.2 on 2018-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyusaapp', '0064_auto_20180923_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='flag',
            new_name='imported_and_logged_in',
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('C4', 'Category 4'), ('C3', 'Category 3'), ('C5', 'Category 5'), ('C1', 'Category 1'), ('C2', 'Category 2')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyCategory',
            field=models.CharField(choices=[('b2c', 'Business-to-Consumer'), ('b2b', 'Business-to-Business')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CompanyType',
            field=models.CharField(choices=[('wholesale', 'Wholesale'), ('retail', 'Retail'), ('service', 'Service'), ('independent', 'Independent'), ('manufacturer', 'Manufacturer')], default='manufacturer', max_length=12),
        ),
    ]
